### ISSUE TITLE
Bluetooth turned off

### ISSUE THREAD

**Issue by Kaythaltes** [bareboat-necessities/lysmarine_gen#120]
I'm not able to turn on Bluetooth. When I try in settings I can change the switch but it keeps saying 'Bluetooth turned off and no devices are shown. When I hoover the mouse over the Bluetooth sing in the top menu it shows 'Bluetooth active'
![16324953470103853243532434553263](https://user-images.githubusercontent.com/91333701/134696040-e2eb5b50-7edb-4ec2-8bc4-44a8a27f3465.jpg)

**Comment by ericrouah** [comment]
This is same for me.

**Comment by mgrouch** [comment]
Might be output of these could shed come light:

as root:

rfkill

```
 dmesg | grep hci0

 systemctl status bluetooth

 hciconfig -a

```

**Comment by Kaythaltes** [comment]
![16324999574686365825154990270746](https://user-images.githubusercontent.com/91333701/134707354-3a520e25-ae97-435f-aa6e-1c2df10630d6.jpg)

**Comment by mgrouch** [comment]
Reported 

Here: https://github.com/raspberrypi/linux/issues/4601

and here: https://github.com/raspberrypi/linux/issues/4239

**Comment by mgrouch** [comment]
couple more:

https://github.com/raspberrypi/firmware/issues/1150


https://github.com/raspberrypi/firmware/issues/1539



@ericrouah 
@Kaythaltes 

Is anything else connected to your raspberry pi? Any hats? Any PCBs? SSD boards?
Anything that uses UART of raspberry pi?

**Comment by ericrouah** [comment]
Nothing yet connected to a bare Raspberry Pi 4/8GB

**Comment by mgrouch** [comment]
@ericrouah 


> Nothing yet connected to a bare Raspberry Pi 4/8GB

If you comment out

arm_64bit=1

in /boot/config.txt

do you still have that issue after reboot?

thanks

**Comment by ericrouah** [comment]
this is the results 👍 
user@lysmarine:/var/www/bbn-launcher $ cd /..
user@lysmarine:/ $ bluetoothctl
Agent registered
[bluetooth]# power on
Failed to set power on: org.bluez.Error.Failed

**Comment by ericrouah** [comment]
> @ericrouah
> 
> > Nothing yet connected to a bare Raspberry Pi 4/8GB
> 
> If you comment out
> 
> arm_64bit=1
> 
> in /boot/config.txt
> 
> do you still have that issue after reboot?
> 
> thanks

I done this and nothing changed

**Comment by ericrouah** [comment]
after uncomment arm_64bit=1 and reboot
I get 
user@lysmarine:/var/www/bbn-launcher $ cd /..
user@lysmarine:/ $ bluetoothctl
Agent registered
[bluetooth]# power on
Failed to set power on: org.bluez.Error.Failed
[bluetooth]# 

@mgrouch this looks as same

**Comment by ericrouah** [comment]
if I test

user@lysmarine:/ $ /usr/bin/btattach -B/dev/ttyAMA0 -Pbcm -S115200
Attaching Primary controller to /dev/ttyAMA0
Failed to open serial port: Device or resource busy
No controller attached
user@lysmarine:/ $

**Comment by ericrouah** [comment]
@Kaythaltes I have same results in the request done like this one 👍  https://github.com/bareboat-necessities/lysmarine_gen/issues/120#issuecomment-926754865

**Comment by mgrouch** [comment]
I’ve narrowed this down. 
If I turn off pypilot services
then Bluetooth works. 
now question what is pypilot doing
to break it

**Comment by mgrouch** [comment]
Report filed here now 

https://github.com/pypilot/pypilot/issues/108

**Comment by mgrouch** [comment]
For a fix try

sudo sed -i 's/ttyAMA0/serial0/' "$(find /usr/local/lib -name serialprobe.py)"

and reboot

**Comment by mgrouch** [comment]
fixed in main branch of BBN OS on github

**Comment by ericrouah** [comment]
AFter I done that, the result is :

***@***.***:/ $ systemctl status bluetooth
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled;
vendor preset: enabled)
   Active: active (running) since Sat 2021-09-25 00:14:51 BST; 2min 26s ago
     Docs: man:bluetoothd(8)
 Main PID: 1125 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/bluetooth.service
           └─1125 /usr/lib/bluetooth/bluetoothd

Sep 25 00:14:51 lysmarine systemd[1]: Started Bluetooth service.
Sep 25 00:14:51 lysmarine bluetoothd[1125]: Starting SDP server
Sep 25 00:14:51 lysmarine bluetoothd[1125]: Bluetooth management
interface 1.18 initialized
Sep 25 00:14:51 lysmarine bluetoothd[1125]: Sap driver initialization failed.
Sep 25 00:14:51 lysmarine bluetoothd[1125]: sap-server: Operation not
permitted (1)
Sep 25 00:14:51 lysmarine bluetoothd[1125]: Failed to set privacy:
Rejected (0x0b)
Sep 25 00:15:17 lysmarine bluetoothd[1125]: Endpoint registered:
sender=:1.35 path=/MediaEndpoint/A2DPSource
Sep 25 00:15:17 lysmarine bluetoothd[1125]: Endpoint registered:
sender=:1.35 path=/MediaEndpoint/A2DPSink
Sep 25 00:15:24 lysmarine bluetoothd[1125]: Failed to set mode: Failed (0x03)
Sep 25 00:15:41 lysmarine bluetoothd[1125]: Failed to set mode: Failed (0x03)
***@***.***:/ $

**Comment by mgrouch** [comment]
You need to run second line too.
I’ve edited my post since I first posted it. 

It fixes the issue. sorry I was too fast and didn’t post correct fix initially.

**Comment by ericrouah** [comment]
Yes I used the two command lines. And the result is same.

**Comment by ericrouah** [comment]
user@lysmarine:~ $ systemctl status bluetooth
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2021-09-25 00:38:40 BST; 6min ago
     Docs: man:bluetoothd(8)
 Main PID: 1122 (bluetoothd)
   Status: "Running"
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/bluetooth.service
           └─1122 /usr/lib/bluetooth/bluetoothd

Sep 25 00:38:40 lysmarine bluetoothd[1122]: Bluetooth management interface 1.18 initialized
Sep 25 00:38:40 lysmarine bluetoothd[1122]: Sap driver initialization failed.
Sep 25 00:38:40 lysmarine bluetoothd[1122]: sap-server: Operation not permitted (1)
Sep 25 00:38:40 lysmarine bluetoothd[1122]: Failed to set privacy: Rejected (0x0b)
Sep 25 00:39:06 lysmarine bluetoothd[1122]: Endpoint registered: sender=:1.34 path=/MediaEndpoint/A2DPSource
Sep 25 00:39:06 lysmarine bluetoothd[1122]: Endpoint registered: sender=:1.34 path=/MediaEndpoint/A2DPSink
Sep 25 00:39:19 lysmarine bluetoothd[1122]: Failed to set mode: Failed (0x03)
Sep 25 00:39:31 lysmarine bluetoothd[1122]: Failed to set mode: Failed (0x03)
Sep 25 00:40:03 lysmarine bluetoothd[1122]: Failed to set mode: Failed (0x03)
Sep 25 00:42:57 lysmarine bluetoothd[1122]: Failed to set mode: Failed (0x03)
user@lysmarine:~ $

**Comment by mgrouch** [comment]
Can you post command lines you used?
Thanks

**Comment by mgrouch** [comment]
Or better at this point the whole file  serialprobe.py

**Comment by mgrouch** [comment]
Did you run these ???

```
sudo sed -i 's/ttyAMA0/serial1/' "$(find /usr/local/lib -name serialprobe.py)"
sudo sed -i "s/'ttyAMA'//" "$(find /usr/local/lib -name serialprobe.py)"
```

**Comment by mgrouch** [comment]
In your serialprobe.py

Line 330 needs to look like this:
`
if device == '/dev/serial1' and name != 'servo':`

and  line  71 like this:

`     devicesp = []`

and its a fix I've tested already on arm64 kernel and arm32

Thanks

**Comment by mgrouch** [comment]
ok. I did more testing.
What I see sometimes it works sometimes it doesn't
It looks like pypilot code still finding and probing bluetooth device instead of serial port.
The probing code also goes via different paths under /dev/ filesystem.

At this instead of my quick fix I think it's better if it is done properly in pypilot code.

Thanks for reporting this. Without it the issue would still be hanging.
Do you even need pypilot for your use case?

Thanks

**Comment by Kaythaltes** [comment]
Problem seems to be solved with this fix.
Thanks

Op za 25 sep. 2021 02:20 schreef Mikhail Grushinskiy <
***@***.***>:

**Comment by mgrouch** [comment]
@ericrouah 
@Kaythaltes 

Better fix is committed into main of https://github.com/bareboat-necessities/lysmarine_gen/blob/master/install-scripts/4-server/files/blacklist_serial_ports

Only installing blacklist_serial_ports in required after all.

into /home/pypilot/.pypilot/

**Comment by ericrouah** [comment]
I am sorry but I cannot do that. The folder /home/pypilot/.pypilot/ is owned by --system (pypilot) and as a user I can only read it.

**Comment by mgrouch** [comment]
@ericrouah 

sudo su
su - pypilot 

That will make you a pypilot user.

**Comment by ericrouah** [comment]
and yes it works !!!
Thank you for your patience ...

**Comment by Kaythaltes** [comment]
Sorry but I don't have too much experience with Linux.
How to install this file?

Op za 25 sep. 2021 19:08 schreef Mikhail Grushinskiy <
***@***.***>:

**Comment by mgrouch** [comment]
> Sorry but I don't have too much experience with Linux. How to install this file? Op za 25 sep. 2021 19:08 schreef Mikhail Grushinskiy < ***@***.***>:
> […](#)

By install I meant just copy.
