### ISSUE TITLE
Two finger touch zoom doesn't work with OpenCPN

### ISSUE THREAD

**Issue by mgrouch** [bareboat-necessities/lysmarine_gen#13]
While I was able to implement a fix it required use of unreleased upstream libraries.

WxWidgets need to release version 3.2
and OpenCPN has to be compiled with it and with GTK3 support
(so do not expect a fix soon)

More on the fix and existing patch from me in the C++ code

https://github.com/OpenCPN/OpenCPN/issues/2057

Realistically it's not a big usability issue on touchscreen as '+' and '-' icons do work.
Right click emulation work fine with bbn patched version of evdev-rce.
(which is more required for a touchscreen)

**Comment by mgrouch** [comment]
Not a release stopper

**Comment by tbultel** [comment]
Hi, using your master branch, I have also noticed the weird pan event, received instead of the zoom event,
when using 2 fingers. The zoom event only comes when using 3 fingers. Did you find out why ?

**Comment by mgrouch** [comment]
I remember that was on gtk2 and not on gtk3

**Comment by tbultel** [comment]
Hi, I confirm this happens with gtk3 as well. Reading the code of wxwidgets tells us that they apparently do the things the right way, and, moreover, their "event" test sample for gesture works like a charm. They do no use opengl, though.

**Comment by tbultel** [comment]
By the way, despite of the need for 3 fingers, I have managed to get a better user experience of zooming, with that implementation of the OnZoom callback. The idea is that the given facture from gesture event is always relative to gesture start position, and has to be converted to something relative to the current level of map zoom:

void ChartCanvas::OnZoom(wxZoomGestureEvent& event)
{

    static double vps=1.0;
    double factor = event.GetZoomFactor();
    wxPoint pos = event.GetPosition();

    if (event.IsGestureStart()) {
        vps = GetVPScale();
    }
   
    double current_vps = GetVPScale();

    double wanted_factor = vps/current_vps*factor;

    ZoomCanvas( wanted_factor, true, false );

}

The static variable should be moved to a data member, of course. Next improvement is to have the zoom centered on the middle of the 2 fingers.

I also wanted to say that this zooming feature is a key one, as far as I am concerned. Even when setting the "+" and "-' buttons biggers, I do no find them convenient, when sailing, and most people are accustomed to zoom with fingers nowadays, due to smartphones (and that is what the android opencpn version does) .

**Comment by tbultel** [comment]
Update: modifying the "penguin" sample in wxwidgets, to add gesture events, works fine (pan with 1 finger, zoom with 2)

**Comment by tbultel** [comment]
FYI, I finally managed to have everything working, including the context menu without the need for an external program. 

https://github.com/OpenCPN/OpenCPN/pull/2333

**Comment by mgrouch** [comment]
I got it working even with un modified 
OpenCPN with latest twofing. Needs more testing on BBN OS.

**Comment by mgrouch** [comment]
Fixed in BBN OS 2021-09-01
